name: Build and Deploy ASP.NET Core App to Azure - PorscheDealership

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Porsche_CarDealerhip_Project/Porsche_CarDealerhip_Project/Porsche_CarDealerhip_Project.csproj

    - name: Build project
      run: dotnet build Porsche_CarDealerhip_Project/Porsche_CarDealerhip_Project/Porsche_CarDealerhip_Project.csproj --configuration Release

    - name: Publish project
      run: dotnet publish Porsche_CarDealerhip_Project/Porsche_CarDealerhip_Project/Porsche_CarDealerhip_Project.csproj --configuration Release --output publish_output

    - name: Zip publish output
      run: Compress-Archive -Path publish_output/* -DestinationPath publish.zip

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: PorscheDealership
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PORSCHEDEALERSHIP }}
        package: publish.zip
