name: Build and Deploy ASP.NET Core App to Azure Web App - PorscheDealership

on:
  push:
    branches:
      - main  # or 'master' if that's your branch name
  workflow_dispatch: # allow manual trigger

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' #  LOCK to .NET 8 LTS

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release

    - name: Publish Project
      run: dotnet publish -c Release -o publish_output

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'PorscheDealership' #  your Azure Web App Name
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PORSCHEDEALERSHIP }}
        package: publish_output
