name: Build and Deploy ASP.NET Core App to Azure Web App - PorscheDealership

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore ./PorscheDealership/PorscheDealership.csproj

    - name: Build Project
      run: dotnet build ./PorscheDealership/PorscheDealership.csproj --configuration Release

    - name: Publish Project
      run: dotnet publish ./PorscheDealership/PorscheDealership.csproj -c Release -o publish_output

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'PorscheDealership'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PORSCHEDEALERSHIP }}
        package: publish_output
